name: bindplane-prometheus
type: Microsoft.App/containerApps
location: eastus
properties:
  managedEnvironmentId: redacted
  configuration:
    activeRevisionsMode: Single
    ingress:
      external: false
      allowInsecure: true
      targetPort: 9090
  template:
    containers:
      - name: prometheus
        image: ghcr.io/observiq/bindplane-prometheus:1.94.3
        resources:
          cpu: 2.0
          memory: 4Gi
        volumeMounts:
          - volumeName: prometheus-data
            mountPath: /prometheus
    volumes:
      - name: prometheus-data
        storageType: AzureFile
        storageName: prometheus-pv
    scale:
      minReplicas: 1
      maxReplicas: 1
